#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow http
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx start 
