#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
sudo service nginx start 
