#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
