#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow http
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html/;
        internal;
    }
}" > /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
