#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 1176-web-01 54.172.160.86:80 check
    server 1176-web-02 34.230.20.37:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
