#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
DATE=$(date +%d-%m-%Y)
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf "${DATE}.tar.gz" backup.sql
