#!/usr/bin/env bash
# Displays Holberton School 10 times, 9th iteration Holberton School,Hi new line.
cnt=1
while [ $cnt -le 10 ]
do
	echo "Holberton School"
	if [ $cnt -eq 9 ]
	then
		echo "Hi"
	fi
	((cnt++))
done
