#!/usr/bin/env bash
# Displays Holberton School 10 times, 9th iteration Holberton School,Hi new line.
i=1
while [ $i -le 10 ]
do
	echo "Holberton School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
