#!/usr/bin/env bash
# Script that loops from 1 to 10 and: bad luck 4th, good luck 8th, Holberton School others
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then 
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done
